"""Twaky CLI — orchestrates ingest, projector, replay, agent."""

from __future__ import annotations

import asyncio

import typer

from twaky.config import settings

app = typer.Typer(help="Twaky — graph agentic brick for Twake.")


@app.command()
def ingest() -> None:
    """Consume RabbitMQ fanouts and append to event_log."""
    from twaky.ingest import run

    asyncio.run(run())


@app.command()
def project(
    batch: int = typer.Option(50, help="Max events per batch."),
    once: bool = typer.Option(False, help="Process one batch and exit."),
) -> None:
    """Project pending event_log rows into the AGE graph."""
    from twaky.projector import run

    run(batch_size=batch, once=once)


@app.command()
def replay(
    from_id: int = typer.Option(
        1, "--from", help="Restart projection from this event_log id."
    ),
) -> None:
    """Mark events as pending again so the projector re-runs them."""
    from twaky.projector import replay_from

    n = replay_from(from_id)
    typer.echo(f"marked {n} rows as pending")


@app.command()
def ask(
    question: str,
    session: str = typer.Option(
        None, help="Langfuse session_id to group related asks."
    ),
    user: str = typer.Option(None, help="Langfuse user_id (Users tab)."),
    tag: list[str] = typer.Option(None, help="Langfuse tag (repeatable)."),  # noqa: B008
) -> None:
    """Ask the graph a natural-language question via the LangChain chain."""
    from twaky.agent import ask as _ask

    result = _ask(question, session_id=session, user_id=user, tags=tag or None)
    typer.echo(result)


@app.command()
def verify(
    uid: str = typer.Option("twaky-verify-1", help="Synthetic event UID."),
) -> None:
    """Publish a synthetic event on calendar:event:created."""
    from twaky.verify_publish import publish_synthetic

    asyncio.run(publish_synthetic(uid))
    typer.echo(f"published synthetic event uid={uid}")


@app.command()
def demo(
    uid: str = typer.Option(None, help="Event UID (autogenerated if omitted)."),
    summary: str = typer.Option(
        "Weekly team sync — Twake demo", help="Event summary/title."
    ),
    meet_url: str = typer.Option(
        None, help="Visio URL (defaults to meet.${BASE_DOMAIN}/room/<uid>)."
    ),
    question: str = typer.Option(
        None,
        help="Question to ask the agent after publish (default: about the visio URL).",
    ),
    wait_s: int = typer.Option(3, help="Seconds to wait for projection before asking."),
    session: str = typer.Option(None, help="Langfuse session_id for grouping."),
    user: str = typer.Option(None, help="Langfuse user_id."),
) -> None:
    """End-to-end demo: publish a visio meeting event, then ask the graph agent."""
    import time
    import uuid as _uuid

    from twaky.agent import ask as _ask
    from twaky.verify_publish import publish_meeting

    uid = uid or f"demo-{_uuid.uuid4().hex[:8]}"
    meet_url = meet_url or f"https://meet.twake-dev.maudet.cloud/room/{uid}"
    question = question or f"What is the visio URL for the event with uid {uid}?"

    typer.echo(
        f"\n▶ publishing event uid={uid}  summary={summary!r}\n  meet={meet_url}\n"
    )
    asyncio.run(publish_meeting(uid, summary, meet_url))
    typer.echo(f"◷ waiting {wait_s}s for the projector...")
    time.sleep(wait_s)
    typer.echo(f"\n? asking the agent: {question}\n")
    result = _ask(question, session_id=session, user_id=user, tags=["demo"])
    typer.echo(str(result))


@app.command()
def env() -> None:
    """Dump the effective configuration (secrets redacted)."""
    d = settings.model_dump()
    for k in ("twaky_pg_password", "langfuse_secret_key"):
        if d.get(k):
            d[k] = "***"
    for k in sorted(d):
        typer.echo(f"{k}={d[k]}")


if __name__ == "__main__":
    app()
