#!/usr/bin/env bash
# Write a .env good enough to boot the stack in CI.
#
# docker-compose.yml declares `env_file: [.env]` on every Python service, so
# `docker compose up` aborts with "env file .env not found" on a fresh
# checkout — CI has no .env. This script produces one.
#
# The values below are PUBLIC, FIXED, AND FAKE. They exist so containers start;
# they are worthless anywhere a real secret is needed. Never copy this file's
# output to a deployment — generate real values per .env.example.
#
# Usage (from the repo root):
#   bash scripts/ci-env.sh
set -euo pipefail

if [ -f .env ]; then
    echo "scripts/ci-env.sh: .env already exists, refusing to overwrite" >&2
    exit 1
fi

cat > .env <<'ENVEOF'
# Generated by scripts/ci-env.sh — CI only. Fake, public, fixed values.
BASE_DOMAIN=ci.local

# --- Postgres+AGE. All three passwords are consumed by sql/*.sh at first boot.
TWAKY_PG_HOST=twaky-pg
TWAKY_PG_PORT=5432
TWAKY_PG_DB=twaky
TWAKY_PG_USER=twaky
TWAKY_PG_PASSWORD=ci-postgres-not-a-secret
LANGFUSE_PG_DB=langfuse
LANGFUSE_PG_USER=langfuse
LANGFUSE_PG_PASSWORD=ci-langfuse-not-a-secret
METABASE_PG_DB=metabase
METABASE_PG_USER=metabase
METABASE_PG_PASSWORD=ci-metabase-not-a-secret

# --- Required by Settings (no default) ---
TWAKY_OWNER_EMAIL=owner@ci.local

# --- API. The session secret must clear check_session_secret's 32-byte floor
#     or twaky-api refuses to start (see src/twaky/api/session.py).
API_BASE_URL=http://twaky-api:8000
API_SESSION_SECRET=ci0000000000000000000000000000000000000000000000000000000000000f
API_OIDC_CLIENT_ID=twaky-api
API_OIDC_CLIENT_SECRET=ci-not-a-secret
API_OIDC_ISSUER=http://oidc.ci.local/

# --- Fernet key for at-rest secrets. Valid shape, no value.
TWAKY_SECRET_KEY=Y2ktbm90LWEtcmVhbC1rZXktMDEyMzQ1Njc4OWFiY2Q=

# --- Nothing in CI talks to these, but compose interpolates them. ---
RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/%2F
MODEL=openai/gpt-4o-mini
ENVEOF

echo "scripts/ci-env.sh: wrote .env (CI placeholder values)"
