/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Missions
         * @description List missions for the instance owner.
         *
         *     By default only live (non-terminal) missions are returned.
         *     Pass ``include_terminal=true`` to include done/failed/cancelled missions.
         */
        get: operations["list_missions_missions_get"];
        put?: never;
        /**
         * Declare
         * @description Declare a new mission. The daemon will pick it up via NOTIFY.
         */
        post: operations["declare_missions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{mid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mission
         * @description Get a single mission by ID.
         */
        get: operations["get_mission_missions__mid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{mid}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Mission
         * @description Resume a mission awaiting user input.
         */
        post: operations["resume_mission_missions__mid__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{mid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Mission
         * @description Cancel a mission.
         */
        post: operations["cancel_mission_missions__mid__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{mid}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mission Trace
         * @description Redirect to the mission's Langfuse session.
         */
        get: operations["mission_trace_missions__mid__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login
         * @description Kick off the OIDC Authorization Code + PKCE flow.
         */
        get: operations["login_oauth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback
         * @description Handle the OIDC provider's callback, set session, redirect.
         */
        get: operations["callback_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Purge session + redirect to LemonLDAP end-session endpoint.
         */
        post: operations["logout_oauth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/jmap/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jmap Login
         * @description Kick off the JMAP OAuth Authorization Code + PKCE flow.
         */
        get: operations["jmap_login_oauth_jmap_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/jmap/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jmap Callback
         * @description Handle JMAP OAuth provider callback, exchange code, store credential.
         */
        get: operations["jmap_callback_oauth_jmap_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Agent */
        patch: operations["patch_agent_agents__agent_id__patch"];
        trace?: never;
    };
    "/agents/{agent_id}/default_prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Default Prompt */
        get: operations["get_default_prompt_agents__agent_id__default_prompt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_skills_get"];
        put?: never;
        /** Create Skill */
        post: operations["create_skill_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill */
        get: operations["get_skill_skills__skill_id__get"];
        put?: never;
        post?: never;
        /** Delete Skill */
        delete: operations["delete_skill_skills__skill_id__delete"];
        options?: never;
        head?: never;
        /** Patch Skill */
        patch: operations["patch_skill_skills__skill_id__patch"];
        trace?: never;
    };
    "/skills/{skill_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Skill */
        post: operations["test_skill_skills__skill_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sentinels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sentinels
         * @description Return all sentinels with 24-hour run statistics.
         */
        get: operations["list_sentinels_sentinels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sentinels/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Detail
         * @description Return the full detail for a single sentinel run.
         */
        get: operations["get_run_detail_sentinels_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sentinels/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sentinel
         * @description Return the full detail for a single sentinel.
         */
        get: operations["get_sentinel_sentinels__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Sentinel
         * @description Toggle enabled state or update config_values for a sentinel.
         *
         *     If ``config_values`` is provided, it is validated against the sentinel's
         *     ``config_schema`` using JSON Schema Draft 2020-12 before persisting.
         *     Returns 422 with code ``validation_failed`` on schema violations.
         */
        patch: operations["patch_sentinel_sentinels__name__patch"];
        trace?: never;
    };
    "/sentinels/{name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List sentinel runs, newest first.
         *
         *     Accepts optional pagination parameters:
         *     - ``limit``: 1..500 (default 100)
         *     - ``before``: ISO-8601 timestamp cursor
         */
        get: operations["list_runs_sentinels__name__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rules
         * @description Return all rules ordered by priority ASC.
         *
         *     When ``enabled=true``, delegates to ``list_all(enabled_only=True)`` to
         *     filter at the DB level.  When absent or ``enabled=false``, fetches all
         *     rows and filters client-side so the FE can decide.
         */
        get: operations["list_rules_mail_sentinel_rules_get"];
        put?: never;
        /**
         * Create Rule
         * @description Create a new mail rule with full validation.
         *
         *     Returns 422 with code ``validation_failed`` on service-layer rejections.
         */
        post: operations["create_rule_mail_sentinel_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rule
         * @description Return the full detail for a single rule.
         */
        get: operations["get_rule_mail_sentinel_rules__rule_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Rule
         * @description Delete a rule by id. Returns 404 if not found.
         */
        delete: operations["delete_rule_mail_sentinel_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Rule
         * @description Apply a partial patch to a rule.
         *
         *     Returns 422 with ``validation_failed`` on empty body or invalid fields.
         *     Returns 404 with ``mail_rule_not_found`` if the rule does not exist.
         */
        patch: operations["patch_rule_mail_sentinel_rules__rule_id__patch"];
        trace?: never;
    };
    "/mail-sentinel/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Memories
         * @description Return recently created memories, optionally filtered by scope.
         */
        get: operations["list_memories_mail_sentinel_memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/learned-patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Learned Patterns
         * @description Return all learned patterns, optionally filtered to active ones.
         */
        get: operations["list_learned_patterns_mail_sentinel_learned_patterns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/learned-patterns/{sender_email}/{rule_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Forget Pattern
         * @description Forget a learned pattern. Silently succeeds even if the row does not exist.
         */
        delete: operations["forget_pattern_mail_sentinel_learned_patterns__sender_email___rule_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/rules/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose Rule
         * @description Simulate a proposed rule against historical spam decisions.
         *
         *     Returns a preview of how many recent decisions would have matched the
         *     proposed rule, which existing rules would shadow it, and up to 10 example
         *     rows — without persisting anything.
         */
        post: operations["propose_rule_mail_sentinel_rules_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Memory
         * @description Toggle a memory between permanent (persist=True) and 7-day TTL (persist=False).
         */
        patch: operations["patch_memory_mail_sentinel_memories__memory_id__patch"];
        trace?: never;
    };
    "/mail-sentinel/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Observations
         * @description Return recently recorded observations ordered by observed_at DESC.
         */
        get: operations["list_observations_mail_sentinel_observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Auth Status
         * @description Return the current OAuth connection status for the mail sentinel.
         *
         *     Returns ``connected=false`` with all nullable fields as ``null`` when no
         *     credential row exists. Returns ``connected=true`` plus the stored metadata
         *     fields when a credential row is present (access/refresh tokens are NOT
         *     included in the response — only metadata).
         */
        get: operations["get_auth_status_mail_sentinel_auth_get"];
        put?: never;
        post?: never;
        /**
         * Delete Auth
         * @description Delete the OAuth credential for the mail sentinel.
         *
         *     Idempotent: silently succeeds if no credential row exists.
         *     The delete trigger fires a NOTIFY on ``oauth_credential_changed`` so the
         *     in-process sentinel stops polling until the owner reconnects.
         */
        delete: operations["delete_auth_mail_sentinel_auth_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Auth
         * @description Force an immediate token refresh and return the updated auth status.
         *
         *     Returns 409 with code ``oauth_credential_not_found`` if no credential row
         *     exists. Returns 502 with code ``refresh_failed`` if the token endpoint
         *     rejects the refresh (e.g. ``invalid_grant``).
         */
        post: operations["refresh_auth_mail_sentinel_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/spam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Spam
         * @description Return recent spam decisions ordered by decided_at DESC.
         *
         *     Optionally filter by ``bucket`` (``spam``, ``newsletter``,
         *     ``phishing-alert``) and/or cursor ``before`` (ISO-8601 datetime).
         *     ``limit`` is bounded 1..500, defaulting to 50.
         *
         *     Pass ``with_provenance=true`` to populate ``origin_mailbox_id`` and
         *     ``origin_mailbox_role`` fields (omitted by default for backward compat).
         */
        get: operations["list_spam_mail_sentinel_spam_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/spam/{decision_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore
         * @description Restore a spam-archived email to the inbox.
         *
         *     JMAP-first two-phase: patches keywords on the JMAP server before touching
         *     the DB, so a JMAP failure leaves state consistent (DB not modified).
         *
         *     Error codes
         *     -----------
         *     404 spam_decision_not_found
         *         No decision row with the given id.
         *     409 already_restored
         *         The decision was already restored.
         *     502 jmap_restore_failed
         *         JMAP server returned an error; DB was not modified.
         */
        post: operations["restore_mail_sentinel_spam__decision_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/spam/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Return aggregated spam decision counts for the last ``days`` days.
         *
         *     Returns counts for ``spam``, ``newsletter``, ``phishing_alert``,
         *     ``restored``, and ``total_processed`` buckets.
         */
        get: operations["get_stats_mail_sentinel_spam_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mail-sentinel/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Mail Runs
         * @description List the N most recent mail-pipeline runs, newest first.
         *
         *     Each row includes the base ``sentinel_run`` fields plus the linked
         *     ``mail_sentinel_spam_decision`` (bucket + signal_source) when the
         *     ``spam_triage`` node classified this email. Uses the ``event_ref``
         *     on the run (which is the JMAP email id) as the join key.
         */
        get: operations["list_mail_runs_mail_sentinel_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Agent */
        Agent: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "orchestrator" | "specialist";
            /** System Prompt */
            system_prompt: string;
            /** Model */
            model: string | null;
            /** Temperature */
            temperature: number | null;
            /** Effective Model */
            effective_model: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AgentSummary */
        AgentSummary: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "orchestrator" | "specialist";
            /** Model */
            model: string | null;
            /** Temperature */
            temperature: number | null;
            /** Effective Model */
            effective_model: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AgentUpdate
         * @description Partial update. All fields optional; empty body → 422 (see router).
         */
        AgentUpdate: {
            /** System Prompt */
            system_prompt?: string | null;
            /** Model */
            model?: string | null;
            /** Temperature */
            temperature?: number | null;
        };
        /** AuthStatus */
        AuthStatus: {
            /** Connected */
            connected: boolean;
            /** Provider */
            provider?: string | null;
            /** Account Email */
            account_email?: string | null;
            /** Account Name */
            account_name?: string | null;
            /** Session Url */
            session_url?: string | null;
            /** Access Token Expires At */
            access_token_expires_at?: string | null;
            /** Last Refresh At */
            last_refresh_at?: string | null;
            /** Last Refresh Error */
            last_refresh_error?: string | null;
        };
        /** CancelBody */
        CancelBody: {
            /** Reason */
            reason: string;
        };
        /** DeclareBody */
        DeclareBody: {
            /** Intent Text */
            intent_text: string;
        };
        /** DefaultPromptResponse */
        DefaultPromptResponse: {
            /** System Prompt */
            system_prompt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LearnedPatternSummary
         * @description Summary of a mail_sentinel_learned_pattern row.
         */
        LearnedPatternSummary: {
            /** Id */
            id: string;
            /** Sender Email */
            sender_email: string;
            /** Rule Name */
            rule_name: string;
            /** Confidence */
            confidence: number;
            /** Evidence Count */
            evidence_count: number;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Confirmed
             * Format: date-time
             */
            last_confirmed: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * MailMemorySummary
         * @description Summary of a mail_sentinel_memory row (evidence omitted).
         */
        MailMemorySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Scope */
            scope: string;
            /** Scope Value */
            scope_value: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** Confidence */
            confidence?: number | null;
            /** Mission Id */
            mission_id?: string | null;
        };
        /**
         * MailRuleCreate
         * @description Payload for POST /mail-sentinel/rules.
         */
        MailRuleCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Conditions
             * @default []
             */
            conditions: {
                [key: string]: unknown;
            }[];
            /**
             * Combinator
             * @default OR
             */
            combinator: string;
            /** Actions */
            actions: string[];
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Run On Threads
             * @default true
             */
            run_on_threads: boolean;
        };
        /**
         * MailRuleDetail
         * @description Full rule row including conditions, combinator, actions, timestamps.
         */
        MailRuleDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Priority */
            priority: number;
            /** Enabled */
            enabled: boolean;
            /** Run On Threads */
            run_on_threads: boolean;
            /** Action Count */
            action_count: number;
            /** Condition Count */
            condition_count: number;
            /** Conditions */
            conditions: {
                [key: string]: unknown;
            }[];
            /** Combinator */
            combinator: string;
            /** Actions */
            actions: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MailRulePatch
         * @description Partial update payload for PATCH /mail-sentinel/rules/{id}.
         */
        MailRulePatch: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Conditions */
            conditions?: {
                [key: string]: unknown;
            }[] | null;
            /** Combinator */
            combinator?: string | null;
            /** Actions */
            actions?: string[] | null;
            /** Priority */
            priority?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Run On Threads */
            run_on_threads?: boolean | null;
        };
        /**
         * MailRuleProposeRequest
         * @description Payload for POST /mail-sentinel/rules/propose.
         */
        MailRuleProposeRequest: {
            /** Name */
            name: string;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Conditions
             * @default []
             */
            conditions: {
                [key: string]: unknown;
            }[];
            /**
             * Combinator
             * @default OR
             */
            combinator: string;
            /** Actions */
            actions: string[];
            window?: components["schemas"]["ProposeWindow"];
        };
        /**
         * MailRuleProposeResponse
         * @description Response shape for POST /mail-sentinel/rules/propose.
         */
        MailRuleProposeResponse: {
            /** Valid */
            valid: boolean;
            /** Matched Count */
            matched_count: number;
            /** Would Shadow Count */
            would_shadow_count: number;
            /** Matched Examples */
            matched_examples: components["schemas"]["MatchedExample"][];
            /** Would Shadow */
            would_shadow: string[];
            /** Simulation Partial */
            simulation_partial: boolean;
            /** Simulation Partial Reason */
            simulation_partial_reason: string | null;
        };
        /**
         * MailRuleSummary
         * @description Shallow representation used in the rules list endpoint.
         */
        MailRuleSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Priority */
            priority: number;
            /** Enabled */
            enabled: boolean;
            /** Run On Threads */
            run_on_threads: boolean;
            /** Action Count */
            action_count: number;
            /** Condition Count */
            condition_count: number;
        };
        /**
         * MailSentinelRun
         * @description One mail_sentinel run row + resolved spam decision (if any).
         */
        MailSentinelRun: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email Id */
            email_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Outcome */
            outcome: string;
            /** Mission Id */
            mission_id: string | null;
            /** Llm Calls */
            llm_calls: number;
            /** Error Repr */
            error_repr: string | null;
            /** Spam Bucket */
            spam_bucket: string | null;
            /** Spam Signal Source */
            spam_signal_source: string | null;
            /** Spam Decision Id */
            spam_decision_id: string | null;
        };
        /**
         * MatchedExample
         * @description A single matched example row in the propose response.
         */
        MatchedExample: {
            /** Decision Id */
            decision_id: string;
            /** Sender */
            sender: string;
            /** Subject */
            subject: string;
            /** Current Bucket */
            current_bucket: string;
            /** Would Shadow By */
            would_shadow_by: string | null;
        };
        /** MemoryPersistRequest */
        MemoryPersistRequest: {
            /** Persist */
            persist: boolean;
        };
        /** Mission */
        Mission: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Owner Email */
            owner_email: string;
            /** Declared By */
            declared_by: string;
            /**
             * Declared At
             * Format: date-time
             */
            declared_at: string;
            /** Intent Text */
            intent_text: string;
            /** Plan */
            plan?: components["schemas"]["PlanStep"][] | null;
            /** @default declared */
            state: components["schemas"]["MissionState"];
            /** State Reason */
            state_reason?: string | null;
            /** Due At */
            due_at?: string | null;
            /** Artifacts */
            artifacts?: {
                [key: string]: unknown;
            }[];
            /** Langfuse Session Id */
            langfuse_session_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MissionState
         * @enum {string}
         */
        MissionState: "declared" | "planning" | "running" | "awaiting_user" | "done" | "failed" | "cancelled";
        /** ObservationSummary */
        ObservationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email Id */
            email_id: string;
            /** Mailbox Id */
            mailbox_id: string;
            /** Observation Type */
            observation_type: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Extraction Outcome */
            extraction_outcome: string;
            /** Memory Ids */
            memory_ids: string[];
            /** Pattern Ids */
            pattern_ids: string[];
            /** Error Repr */
            error_repr?: string | null;
        };
        /** PlanStep */
        PlanStep: {
            /** Agent */
            agent: string;
            /** Tool */
            tool: string;
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "in_progress" | "done" | "skipped";
        };
        /**
         * ProposeWindow
         * @description Window specification for the propose endpoint.
         */
        ProposeWindow: {
            /**
             * Kind
             * @default recent
             */
            kind: string;
            /**
             * Count
             * @default 200
             */
            count: number;
        };
        /** ResumeBody */
        ResumeBody: {
            /** User Response */
            user_response: {
                [key: string]: unknown;
            };
        };
        /**
         * SentinelDetail
         * @description Full sentinel row including config schema and values.
         */
        SentinelDetail: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
            /** Version */
            version: string;
            /** Config Schema */
            config_schema: {
                [key: string]: unknown;
            };
            /** Config Values */
            config_values: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SentinelPatch
         * @description Partial update payload. Extra keys are rejected.
         */
        SentinelPatch: {
            /** Enabled */
            enabled?: boolean | null;
            /** Config Values */
            config_values?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SentinelRunDetail
         * @description Full run record including trace and error information.
         */
        SentinelRunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sentinel Name */
            sentinel_name: string;
            /** Event Ref */
            event_ref: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ignored" | "processed" | "mission_created" | "delegated" | "error";
            /** Mission Id */
            mission_id: string | null;
            /** Llm Calls */
            llm_calls: number;
            /** Trace */
            trace: {
                [key: string]: unknown;
            }[];
            /** Error Repr */
            error_repr: string | null;
        };
        /**
         * SentinelRunSummary
         * @description One row from ``sentinel_run``, without the heavy fields.
         */
        SentinelRunSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sentinel Name */
            sentinel_name: string;
            /** Event Ref */
            event_ref: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ignored" | "processed" | "mission_created" | "delegated" | "error";
            /** Mission Id */
            mission_id: string | null;
            /** Llm Calls */
            llm_calls: number;
        };
        /**
         * SentinelSummary
         * @description Shallow representation used in the list endpoint.
         */
        SentinelSummary: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Version */
            version: string;
            stats_24h: components["schemas"]["Stats24h"];
        };
        /** Skill */
        Skill: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Python Source */
            python_source: string;
            /** Config Schema */
            config_schema: {
                [key: string]: unknown;
            };
            /** Config Values */
            config_values: {
                [key: string]: unknown;
            };
            /** Bound Agents */
            bound_agents: ("atlas" | "chronos" | "plume" | "iris")[];
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SkillCreate */
        SkillCreate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Python Source */
            python_source: string;
            /** Config Schema */
            config_schema?: {
                [key: string]: unknown;
            };
            /** Config Values */
            config_values?: {
                [key: string]: unknown;
            };
            /** Bound Agents */
            bound_agents?: ("atlas" | "chronos" | "plume" | "iris")[];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * SkillSummary
         * @description Shorter payload for the list endpoint. Omits code + config.
         */
        SkillSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Bound Agents */
            bound_agents: ("atlas" | "chronos" | "plume" | "iris")[];
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SkillTestRequest */
        SkillTestRequest: {
            /** Args */
            args?: {
                [key: string]: unknown;
            };
        };
        /** SkillTestResponse */
        SkillTestResponse: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ok" | "timeout" | "crashed" | "error";
            /** Result */
            result?: unknown;
            /** Message */
            message?: string | null;
        };
        /**
         * SkillUpdate
         * @description Partial update. All fields optional; empty body → 422 (enforced in router).
         */
        SkillUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Python Source */
            python_source?: string | null;
            /** Config Schema */
            config_schema?: {
                [key: string]: unknown;
            } | null;
            /** Config Values */
            config_values?: {
                [key: string]: unknown;
            } | null;
            /** Bound Agents */
            bound_agents?: ("atlas" | "chronos" | "plume" | "iris")[] | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * SpamDecision
         * @description Full representation of a mail_sentinel_spam_decision row.
         */
        SpamDecision: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email Id */
            email_id: string;
            /** Thread Id */
            thread_id: string | null;
            /** Sender Email */
            sender_email: string;
            /** Subject */
            subject: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Bucket */
            bucket: string;
            /** Signal Source */
            signal_source: string;
            /** Score */
            score: number | null;
            /** Reason */
            reason: string | null;
            /** Restored At */
            restored_at: string | null;
            /** Restored By */
            restored_by: string | null;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Origin Mailbox Id */
            origin_mailbox_id?: string | null;
            /** Origin Mailbox Role */
            origin_mailbox_role?: string | null;
        };
        /**
         * SpamStats
         * @description Aggregated counts for the /mail-sentinel/spam/stats endpoint.
         */
        SpamStats: {
            /** Spam */
            spam: number;
            /** Newsletter */
            newsletter: number;
            /** Phishing Alert */
            phishing_alert: number;
            /** Restored */
            restored: number;
            /** Total Processed */
            total_processed: number;
        };
        /**
         * Stats24h
         * @description 24-hour run statistics for a sentinel.
         */
        Stats24h: {
            /** Total */
            total: number;
            /** Errors */
            errors: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_missions_missions_get: {
        parameters: {
            query?: {
                state?: components["schemas"]["MissionState"] | null;
                include_terminal?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    declare_missions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclareBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mission_missions__mid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_mission_missions__mid__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_mission_missions__mid__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mission_trace_missions__mid__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_oauth_login_get: {
        parameters: {
            query?: {
                return_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_oauth_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_oauth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    jmap_login_oauth_jmap_login_get: {
        parameters: {
            query?: {
                return_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jmap_callback_oauth_jmap_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    events_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_agents_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSummary"][];
                };
            };
        };
    };
    get_agent_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_agent_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_default_prompt_agents__agent_id__default_prompt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultPromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSummary"][];
                };
            };
        };
    };
    create_skill_skills_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_skills__skill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_skill_skills__skill_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_skill_skills__skill_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_skill_skills__skill_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sentinels_sentinels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentinelSummary"][];
                };
            };
        };
    };
    get_run_detail_sentinels_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentinelRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sentinel_sentinels__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentinelDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_sentinel_sentinels__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SentinelPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentinelDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_sentinels__name__runs_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentinelRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_mail_sentinel_rules_get: {
        parameters: {
            query?: {
                enabled?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailRuleSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_mail_sentinel_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailRuleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_mail_sentinel_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailRuleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_mail_sentinel_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_rule_mail_sentinel_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailRulePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailRuleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories_mail_sentinel_memories_get: {
        parameters: {
            query?: {
                scope?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailMemorySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_learned_patterns_mail_sentinel_learned_patterns_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnedPatternSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_pattern_mail_sentinel_learned_patterns__sender_email___rule_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sender_email: string;
                rule_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_rule_mail_sentinel_rules_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailRuleProposeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailRuleProposeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_memory_mail_sentinel_memories__memory_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryPersistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailMemorySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_observations_mail_sentinel_observations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auth_status_mail_sentinel_auth_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    delete_auth_mail_sentinel_auth_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_auth_mail_sentinel_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    list_spam_mail_sentinel_spam_get: {
        parameters: {
            query?: {
                bucket?: string | null;
                limit?: number;
                before?: string | null;
                with_provenance?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpamDecision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_mail_sentinel_spam__decision_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpamDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_mail_sentinel_spam_stats_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpamStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mail_runs_mail_sentinel_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailSentinelRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
